### ISSUE TITLE
could not find function "TTipol"

### ISSUE THREAD

**Issue by xuebaliang** [irinagain/mixedCCA#1]
Can you tell me that which package these functions "TTipol", "TCipol", "TBipol", "BCipol", "BBipol" come from??? Thanks!!!

**Comment by irinagain** [comment]
Those functions are internal functions within our package mixedCCA and are used for estimation of bridge function inversion. The user should not have the need to use these functions unless you want to study interpolation specifically. Do you have a particular application in mind that you want to use our R package for?

**Comment by xuebaliang** [comment]
I cannot install the package in the github on my linux server, so I download the whole function in your github and load them. When I use the SPRING to estimate the microbiome interaction network, it need the "mixedcca" package. You say they are internal functions, but I cannot find them in mixedCCA/R folder. can you supply them for me

**Comment by xuebaliang** [comment]
or can you supply a entire R package (like tar.gz file) on your github? Bacause install_github may fail on some linux server. Thanks.

**Comment by GraceYoon** [comment]
We are in the process of submitting our mixedCCA package to CRAN. Once it is accepted by CRAN, you'll be able to download the tar.gz file soon. Thank you!

**Comment by GraceYoon** [comment]
@xuebaliang 
Our R package "mixedCCA" is now available on CRAN: 
https://cran.r-project.org/web/packages/mixedCCA/index.html.
