### ISSUE TITLE
Error installation using R on a mac

### ISSUE THREAD

**Issue by carolynePearl** [irinagain/mixedCCA#3]
I have completely failed to install this package; Here is the error
> devtools::install_github("irinagain/mixedCCA")
Downloading GitHub repo irinagain/mixedCCA@HEAD
✓  checking for file ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpOrGN52/remotes4985b07b300/irinagain-mixedCCA-79ee0ea/DESCRIPTION’ (1.8s)
─  preparing ‘mixedCCA’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (462ms)
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘mixedCCA_1.4.2.tar.gz’
   
Installing package into ‘/Users/bioinformaticslabcomp1/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘mixedCCA’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/Rcpp/include" -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/RcppArmadillo/include" -I/usr/local/opt/llvm/include -fopenmp -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘mixedCCA’
* removing ‘/Users/bioinformaticslabcomp1/Library/R/3.6/library/mixedCCA’
Error: Failed to install 'mixedCCA' from GitHub:
  (converted from warning) installation of package ‘/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T//RtmpOrGN52/file4985678f3b0/mixedCCA_1.4.2.tar.gz’ had non-zero exit status
> 

I then made a Makevars file
CC=gcc$(VER)
CXX=g++$(VER)
CXX11=gcc$(VER)
CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
FLIBS=-L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10

i got this error;

> devtools::install_github("irinagain/mixedCCA")
Downloading GitHub repo irinagain/mixedCCA@HEAD
✓  checking for file ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpOrGN52/remotes498120a1bba/irinagain-mixedCCA-79ee0ea/DESCRIPTION’ (618ms)
─  preparing ‘mixedCCA’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘mixedCCA_1.4.2.tar.gz’
   
Installing package into ‘/Users/bioinformaticslabcomp1/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘mixedCCA’ ...
** using staged installation
** libs
gcc -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/Rcpp/include" -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘mixedCCA’
* removing ‘/Users/bioinformaticslabcomp1/Library/R/3.6/library/mixedCCA’
Error: Failed to install 'mixedCCA' from GitHub:
  (converted from warning) installation of package ‘/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T//RtmpOrGN52/file49855a25996/mixedCCA_1.4.2.tar.gz’ had non-zero exit status

How can you help? Thanks

**Comment by irinagain** [comment]
Can you try installing directly from CRAN and seeing if you have the same issue? This is compiler disconnect, so may take some time to address but we will try to find a solution ASAP

**Comment by irinagain** [comment]
https://cran.r-project.org/web/packages/mixedCCA/index.html

**Comment by GraceYoon** [comment]
Updating clang might work. Please try installing directly from CRAN for now. We'll update CRAN version as soon as possible. Thanks!

**Comment by GraceYoon** [comment]
Now mixedCCA 1.4.3 version is available from CRAN. Please try installing directly from CRAN. Thanks.
