### ISSUE TITLE
Installation failed: dependency not available

### ISSUE THREAD

**Issue by benedil** [irinagain/mixedCCA#6]
Hello, I'm trying to install NetCoMi, which requires SPRING, which requires mixedCCA, and I'm getting the following error:

> > devtools::install_github("irinagain/mixedCCA")
> Downloading GitHub repo irinagain/mixedCCA@HEAD
> Skipping 1 packages not available: chebpol
> v  checking for file 'C:\Users\Test\AppData\Local\Temp\RtmpKac6Me\remotes1c7cd8f1da5\irinagain-mixedCCA-71da206/DESCRIPTION' ... 
> -  preparing 'mixedCCA':
> v  checking DESCRIPTION meta-information ... 
> -  cleaning src
> -  checking for LF line-endings in source and make files and shell scripts (1.2s)
> -  checking for empty or unneeded directories
>    Omitted 'LazyData' from DESCRIPTION
> -  building 'mixedCCA_1.4.6.tar.gz'
>    
> Installing package into ‘C:/Users/Test/Documents/R/win-library/4.1’
> (as ‘lib’ is unspecified)
> ERROR: dependency 'chebpol' is not available for package 'mixedCCA'
> * removing 'C:/Users/Test/Documents/R/win-library/4.1/mixedCCA'

chebpol seems to be a dead package, but I've tried installing the last version of it (from Dec 2019) from the archive and it fails because it won't work with R v4.1.  Is there a way to work around this?

Thank you!
LS

**Comment by irinagain** [comment]
We are unfortunately aware of the issue, but do not have a current workaround. Chebpol is needed for fast computations using multi-linear interpolation, and it does appear to be dead with no response from maintainer. mixedCCA can still work without chebpol but the fast computation version will not be available. We are currently working on mixedCCA quick patch that moves chebpol to suggests and only uses original computation scheme (which is much slower unfortunately but works). I will let you know when that patch is out. As for when we fix the fast version, that may take more time as currently there doesn't not appear to be an alternative in R that can do multi-linear interpolation with 3 or 4 dimensions.

**Comment by benedil** [comment]
Understood, thank you.

**Comment by irinagain** [comment]
The quick patch is out, so it should be installable now from GitHub (and is on the way to CRAN). Be aware it would be relatively slow depending on your application because we had to remove fast multi-linear interpolation approximation until we can find a substitute for chebpol. Thank you.
