### ISSUE TITLE
fast implementation of mixedCCA

### ISSUE THREAD

**Issue by sidchop** [irinagain/mixedCCA#7]
Hi - thanks for developing this great method. Due to data size, I am hoping to use the fast implementation. I see that a fix is being worked on, but was wondering if there is any way to use the fast implementation currently, or has the deprecation of `chebpol` made this currently impossible?
Thanks.

**Comment by irinagain** [comment]
Unfortunately, the depreciation of `chebpol` created a huge issue making "currently" impossible unless you manage to install and make arxived version of `chebpol` work on your machine (then an earlier arxived version of mixedCCA will be fine). The fix without `chebpol` is not trivial as there is no other package (that we know of) that implements 3d or 4d linear interpolation. We are working on figuring it out but it will take time

**Comment by sidchop** [comment]
Ah okay - thanks for your quick response. I'll try archived versions then.

**Comment by irinagain** [comment]
We fixed mixedCCA without chebpol dependency, new version is on Github and CRAN, in case it's still relevant
